---
kind: pipeline
name: run

steps:
  - name: unit tests
    image: mcr.microsoft.com/dotnet/sdk:10.0
    commands:
      - dotnet publish Tests/Tests.csproj -c Release
      - dotnet Tests/bin/Release/net10.0/publish/Tests.dll
